// Code generated by go-swagger; DO NOT EDIT.

// Package restapi 俱乐部等级评定
//
//  俱乐部等级评定系统API
//  Schemes:
//    http
//  Host: localhost:7010
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/zip
//    - application/octet-stream
//    - application/json
//
// swagger:meta
package restapi
