// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetClubFileZipHandlerFunc turns a function with the right signature into a get club file zip handler
type GetClubFileZipHandlerFunc func(GetClubFileZipParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClubFileZipHandlerFunc) Handle(params GetClubFileZipParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetClubFileZipHandler interface for that can handle valid get club file zip params
type GetClubFileZipHandler interface {
	Handle(GetClubFileZipParams, *v1.Principal) middleware.Responder
}

// NewGetClubFileZip creates a new http.Handler for the get club file zip operation
func NewGetClubFileZip(ctx *middleware.Context, handler GetClubFileZipHandler) *GetClubFileZip {
	return &GetClubFileZip{Context: ctx, Handler: handler}
}

/* GetClubFileZip swagger:route GET /v1/file/download/zip monitor getClubFileZip

获取文件

获取文件

*/
type GetClubFileZip struct {
	Context *middleware.Context
	Handler GetClubFileZipHandler
}

func (o *GetClubFileZip) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClubFileZipParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
