// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetClubFileZipOKCode is the HTTP code returned for type GetClubFileZipOK
const GetClubFileZipOKCode int = 200

/*GetClubFileZipOK A successful response.

swagger:response getClubFileZipOK
*/
type GetClubFileZipOK struct {
	/*download file.

	 */
	ContentDisposition string `json:"Content-Disposition"`

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetClubFileZipOK creates GetClubFileZipOK with default headers values
func NewGetClubFileZipOK() *GetClubFileZipOK {

	return &GetClubFileZipOK{}
}

// WithContentDisposition adds the contentDisposition to the get club file zip o k response
func (o *GetClubFileZipOK) WithContentDisposition(contentDisposition string) *GetClubFileZipOK {
	o.ContentDisposition = contentDisposition
	return o
}

// SetContentDisposition sets the contentDisposition to the get club file zip o k response
func (o *GetClubFileZipOK) SetContentDisposition(contentDisposition string) {
	o.ContentDisposition = contentDisposition
}

// WithPayload adds the payload to the get club file zip o k response
func (o *GetClubFileZipOK) WithPayload(payload io.ReadCloser) *GetClubFileZipOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get club file zip o k response
func (o *GetClubFileZipOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClubFileZipOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Content-Disposition

	contentDisposition := o.ContentDisposition
	if contentDisposition != "" {
		rw.Header().Set("Content-Disposition", contentDisposition)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
