// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// User 用户信息
//
// swagger:model User
type User struct {

	// 邮箱
	Avatar string `json:"avatar"`

	// 邮箱
	Email string `json:"email"`

	// id
	// Read Only: true
	ID string `json:"id"`

	// 用户名
	Name string `json:"name"`

	// 邮箱
	NickName string `json:"nickName"`

	// openid
	// Read Only: true
	Openid string `json:"openid"`

	// 电话号码
	Phone string `json:"phone"`

	// 用户密码
	Ps string `json:"ps"`

	// 用户角色
	Role string `json:"role"`

	// unionid
	// Read Only: true
	Unionid string `json:"unionid"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this user based on the context it is used
func (m *User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOpenid(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnionid(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *User) contextValidateOpenid(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "openid", "body", string(m.Openid)); err != nil {
		return err
	}

	return nil
}

func (m *User) contextValidateUnionid(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "unionid", "body", string(m.Unionid)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
